import "./globals.css";
import type { Metadata } from "next";
import { poppinsRegularFont } from "fonts";
import Providers from "@/shared/Providers";
import { IChildren } from "types";

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

const staleBuildRecoveryScript = `
(() => {
  const storageKey = "exclusive-store-build-recovery";
  const retryDelay = 30000;

  const recover = () => {
    const now = Date.now();
    const lastRetry = Number(sessionStorage.getItem(storageKey) || 0);
    if (now - lastRetry < retryDelay) return;

    sessionStorage.setItem(storageKey, String(now));
    const url = new URL(window.location.href);
    url.searchParams.set("__build", String(now));
    window.location.replace(url.toString());
  };

  window.addEventListener("error", (event) => {
    const target = event.target;
    const assetUrl = target && (target.src || target.href) || "";
    const staleAsset = assetUrl.includes("/_next/static/") ||
      assetUrl.includes("/images/") || assetUrl.includes("/icons/");
    const staleChunk = String(event.message || "").includes("ChunkLoadError") ||
      String(event.message || "").includes("Loading chunk");
    if (staleAsset || staleChunk) recover();
  }, true);

  window.addEventListener("unhandledrejection", (event) => {
    const reason = String(event.reason && (event.reason.message || event.reason) || "");
    if (reason.includes("ChunkLoadError") || reason.includes("Loading chunk")) recover();
  });
})();
`;

export default function RootLayout({ children }: IChildren) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: staleBuildRecoveryScript }} />
      </head>
      <body className={`${poppinsRegularFont.className} `}>
        {/* chackra ui providers and recoil */}
        <div className="flex min-h-screen flex-col overflow-x-hidden">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
