"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { homeSalesSwiper, homeBestSellingSwiper, homeProductsSwiper } from "@/data";

type Tab = "overview"|"analytics"|"products"|"stock"|"trash"|"promos"|"orders"|"customers"|"support";
type Product = {id:number;name:string;slug:string;category:string;price:number;old_price:number|null;stock:number;active:boolean;archived?:boolean;description:string};
type ProductForm = {name:string;slug:string;category:string;price:string;old_price:string;stock:string;description:string};
type Promo = {id?:number;code:string;discount_percent:number;active:boolean};
type Order = {id:string;status:string;total:number;customer_name:string;customer_email:string;customer_phone:string;shipping_address:string;created_at:string};
type Customer = {id:string;full_name:string;phone:string;role:string;created_at:string};
type Thread = {id:string;status:string;last_message_at:string};
type PageView = {id:number;visitor_id:string;path:string;entry_path:string;source:string;ref_code:string;referrer:string;device:string;platform:string;created_at:string};

const blank:ProductForm={name:"",slug:"",category:"",price:"",old_price:"",stock:"0",description:""};
const statuses=["new","confirmed","processing","shipped","delivered","cancelled","refunded"];
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9а-яё]+/gi,"-").replace(/^-|-$/g,"");
const toForm=(p:Product):ProductForm=>({name:p.name,slug:p.slug,category:p.category||"",price:String(p.price),old_price:p.old_price==null?"":String(p.old_price),stock:String(p.stock),description:p.description||""});
const productImageMap=new Map([...homeSalesSwiper,...homeBestSellingSwiper,...homeProductsSwiper].map(p=>[p.name.trim().toLowerCase(),p.images[0]]));

export default function AdminDashboard(){
  const supabase=useMemo(()=>getSupabaseBrowserClient(),[]);
  const locale=usePathname().split("/")[1]||"ru";
  const router=useRouter();
  const [tab,setTab]=useState<Tab>("overview");
  const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[saving,setSaving]=useState(false);
  const [message,setMessage]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
  const [products,setProducts]=useState<Product[]>([]),[promos,setPromos]=useState<Promo[]>([]),[orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[threads,setThreads]=useState<Thread[]>([]),[views,setViews]=useState<PageView[]>([]);
  const [form,setForm]=useState<ProductForm>(blank),[editing,setEditing]=useState<Product|null>(null),[editForm,setEditForm]=useState<ProductForm>(blank);
  const [stockDraft,setStockDraft]=useState<Record<number,number>>({}),[promoDraft,setPromoDraft]=useState<Record<string,boolean>>({});
  const [refCode,setRefCode]=useState("partner-01");

  const load=useCallback(async()=>{if(!supabase)return;const [p,pc,o,c,t,v]=await Promise.all([
    supabase.from("products").select("*").order("created_at",{ascending:false}),
    supabase.from("promo_codes").select("*").order("discount_percent"),
    supabase.from("orders").select("*").order("created_at",{ascending:false}),
    supabase.from("profiles").select("id,full_name,phone,role,created_at").order("created_at",{ascending:false}),
    supabase.from("support_threads").select("id,status,last_message_at").order("last_message_at",{ascending:false}),
    supabase.from("page_views").select("*").order("created_at",{ascending:false}).limit(2000),
  ]);setProducts((p.data||[]) as Product[]);setPromos((pc.data||[]) as Promo[]);setOrders((o.data||[]) as Order[]);setCustomers((c.data||[]) as Customer[]);setThreads((t.data||[]) as Thread[]);setViews((v.data||[]) as PageView[]);const error=p.error||pc.error||o.error||c.error||t.error;if(error&&!String(error.message).includes("page_views"))setNotice(error.message)},[supabase]);

  useEffect(()=>{(async()=>{if(!supabase){setMessage("Supabase не подключён");setLoading(false);return}const {data}=await supabase.auth.getUser();if(!data.user){setMessage("Сначала войдите в аккаунт");setLoading(false);return}const {data:profile}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();if(!profile||!["support","manager","admin"].includes(profile.role)){setMessage("Нет доступа к админ-панели");setLoading(false);return}setAllowed(true);await load();setLoading(false)})()},[load,supabase]);
  useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(""),5000);return()=>window.clearTimeout(timer)},[notice]);

  const visible=products.filter(p=>!p.archived&&p.name.toLowerCase().includes(query.toLowerCase()));
  const trash=products.filter(p=>p.archived),inventory=products.filter(p=>!p.archived).sort((a,b)=>Number(a.stock)-Number(b.stock));
  const stats=useMemo(()=>({products:products.filter(p=>!p.archived).length,stock:products.filter(p=>!p.archived).reduce((s,p)=>s+Number(p.stock||0),0),orders:orders.length,newOrders:orders.filter(o=>o.status==="new").length,customers:customers.filter(c=>c.role==="customer").length,support:threads.filter(t=>t.status!=="closed").length}),[products,orders,customers,threads]);
  const analytics=useMemo(()=>{const count=(key:keyof PageView)=>Object.entries(views.reduce((a,v)=>{const k=String(v[key]||"unknown");a[k]=(a[k]||0)+1;return a},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]);const latest=new Map<string,PageView>();views.forEach(v=>{if(!latest.has(v.visitor_id))latest.set(v.visitor_id,v)});const exitCounts=Array.from(latest.values()).reduce((a,v)=>{a[v.path]=(a[v.path]||0)+1;return a},{} as Record<string,number>);return {unique:new Set(views.map(v=>v.visitor_id)).size,sources:count("source"),refs:count("ref_code").filter(([name])=>name!=="unknown"),entries:count("entry_path"),exits:Object.entries(exitCounts).sort((a,b)=>b[1]-a[1]),devices:count("device"),platforms:count("platform"),pages:count("path")}},[views]);
  const payload=(v:ProductForm)=>({name:v.name.trim(),slug:slugify(v.slug||v.name),category:v.category.trim(),description:v.description.trim(),price:Number(v.price),old_price:v.old_price?Number(v.old_price):null,stock:Math.max(0,Number(v.stock))});
  async function addProduct(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);const {error}=await supabase.from("products").insert({...payload(form),active:true,archived:false});if(error)setNotice(error.message);else{setForm(blank);setNotice("Товар добавлен");await load()}setSaving(false)}
  async function saveProduct(e:FormEvent){e.preventDefault();if(!supabase||!editing)return;setSaving(true);const {error}=await supabase.from("products").update(payload(editForm)).eq("id",editing.id);if(error)setNotice(error.message);else{setEditing(null);setNotice("Изменения сохранены");await load()}setSaving(false)}
  async function updateProduct(p:Product,values:Partial<Product>,ok:string){if(!supabase)return;const {error}=await supabase.from("products").update(values).eq("id",p.id);if(error)setNotice(error.message);else{setNotice(ok);await load()}}
  const toggle=(p:Product)=>updateProduct(p,{active:!p.active},p.active?"Товар скрыт":"Товар опубликован");
  const archive=(p:Product)=>confirm(`Переместить «${p.name}» в корзину?`)&&updateProduct(p,{active:false,archived:true},"Товар в корзине");
  const restore=(p:Product)=>updateProduct(p,{active:true,archived:false},"Товар восстановлен");
  async function deleteForever(p:Product){if(!supabase||!confirm(`Удалить «${p.name}» навсегда?`))return;const {error}=await supabase.from("products").delete().eq("id",p.id);if(error)setNotice(error.message);else{setNotice("Товар удалён");await load()}}
  async function savePromo(p:Promo){if(!supabase)return;const active=promoDraft[p.code]??p.active;const {error}=await supabase.from("promo_codes").update({active}).eq("code",p.code);if(error)setNotice(error.message);else{setPromoDraft(d=>{const next={...d};delete next[p.code];return next});setNotice(active?"Промокод включён":"Промокод отключён");await load()}}
  async function changeStatus(id:string,status:string){if(!supabase)return;const {error}=await supabase.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setNotice(error.message);else await load()}
  async function signOut(){await supabase?.auth.signOut();router.push(`/${locale}/login`)}

  if(loading)return <div className="min-h-[60vh] bg-neutral-100 p-8">Загрузка панели…</div>;
  if(!allowed)return <div className="min-h-[60vh] bg-neutral-100 p-8"><p>{message}</p><Link href={`/${locale}/login`} className="mt-4 inline-block underline">Перейти ко входу</Link></div>;
  const nav:[Tab,string][]=[["overview","Обзор"],["analytics","Аналитика"],["products","Товары"],["stock",`Остатки (${inventory.length})`],["trash",`Корзина (${trash.length})`],["promos","Промокоды"],["orders","Заказы"],["customers","Клиенты"],["support","Поддержка"]];
  const empty=(text:string)=><div className="rounded-2xl border border-dashed border-neutral-300 bg-white p-10 text-center text-neutral-500">{text}</div>;
  const fields=(v:ProductForm,set:(v:ProductForm)=>void)=><div className="grid gap-3">{[["name","Название","text"],["slug","Slug (необязательно)","text"],["category","Категория","text"],["price","Цена","number"],["old_price","Старая цена","number"],["stock","Остаток","number"]].map(([key,ph,type])=><input key={key} required={["name","price","stock"].includes(key)} type={type} min={type==="number"?0:undefined} value={v[key as keyof ProductForm]} onChange={e=>set({...v,[key]:e.target.value})} placeholder={ph} className="rounded-xl border px-4 py-3"/>)}<textarea rows={4} value={v.description} onChange={e=>set({...v,description:e.target.value})} placeholder="Описание" className="rounded-xl border px-4 py-3"/></div>;
  const thumb=(p:Product)=>{const image=productImageMap.get(p.name.trim().toLowerCase());return <div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-neutral-100">{image?<img src={`/images/products/${image}`} alt="" className="h-12 w-12 object-contain"/>:<span className="text-2xl">📦</span>}</div>};
  const productList=(list:Product[],isTrash=false)=>list.length?<div className="grid gap-3">{list.map(p=><article key={p.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div className="flex min-w-0 gap-4">{thumb(p)}<div className="min-w-0"><h4 className="text-lg font-bold">{p.name}</h4><p className="break-all text-sm text-neutral-500">{p.category||"Без категории"} · {p.slug}</p><p className="mt-2"><b>{Number(p.price).toLocaleString("ru-RU")} ₽</b> · Остаток: {p.stock}</p></div></div>{!isTrash&&<span className={`h-fit rounded-full px-3 py-1 text-xs ${p.active?"bg-green-100":"bg-neutral-200"}`}>{p.active?"Опубликован":"Скрыт"}</span>}</div><div className="mt-4 flex flex-wrap gap-2">{isTrash?<><button onClick={()=>restore(p)} className="rounded-full bg-black px-4 py-2 text-sm text-white">Восстановить</button><button onClick={()=>deleteForever(p)} className="rounded-full border border-red-200 px-4 py-2 text-sm text-red-600">Удалить навсегда</button></>:<><button onClick={()=>{setEditing(p);setEditForm(toForm(p))}} className="rounded-full bg-black px-4 py-2 text-sm text-white">Изменить</button><button onClick={()=>toggle(p)} className="rounded-full border px-4 py-2 text-sm">{p.active?"Скрыть":"Опубликовать"}</button><button onClick={()=>archive(p)} className="rounded-full border border-red-200 px-4 py-2 text-sm text-red-600">В корзину</button></>}</div></article>)}</div>:empty(isTrash?"Корзина товаров пуста":"Товары не найдены");

  return <div className="min-h-screen max-w-full overflow-x-hidden bg-neutral-100 text-neutral-900"><div className="mx-auto grid w-full min-w-0 max-w-[1600px] lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="min-w-0 max-w-full overflow-hidden bg-black p-5 text-white lg:min-h-screen lg:p-7"><div className="flex items-center justify-between gap-3 lg:block"><div className="min-w-0"><p className="truncate text-xs uppercase tracking-[.25em] text-white/50">Exclusive Store</p><h1 className="mt-2 text-2xl font-bold">Админ-панель</h1></div><button onClick={signOut} className="shrink-0 rounded-full border border-white/25 px-4 py-2 text-sm lg:hidden">Выйти</button></div><nav className="mt-6 grid w-full min-w-0 grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:flex lg:flex-col">{nav.map(([id,label])=><button key={id} onClick={()=>{setTab(id);setNotice("")}} className={`min-w-0 break-words rounded-xl px-3 py-3 text-left text-sm font-medium sm:text-base ${tab===id?"bg-white text-black":"text-white/70 hover:bg-white/10"}`}>{label}{id==="orders"&&stats.newOrders?` (${stats.newOrders})`:""}</button>)}</nav><button onClick={signOut} className="mt-8 hidden w-full rounded-xl border border-white/25 px-4 py-3 lg:block">Выйти</button></aside>
  <main className="w-full min-w-0 overflow-hidden p-4 sm:p-6 xl:p-10"><header className="mb-7 flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm text-neutral-500">Управление магазином</p><h2 className="break-words text-2xl font-bold sm:text-4xl">{nav.find(([id])=>id===tab)?.[1]}</h2></div><Link href={`/${locale}`} className="shrink-0 rounded-full border bg-white px-5 py-2.5">Открыть сайт</Link></header>{notice&&<div className="mb-5 break-words rounded-xl bg-amber-100 p-4 text-sm">{notice}</div>}
  {tab==="overview"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["Товаров",stats.products],["Остаток, шт.",stats.stock],["Заказов",stats.orders],["Новых заказов",stats.newOrders],["Клиентов",stats.customers],["Обращений",stats.support]].map(([l,v])=><article key={l} className="min-w-0 rounded-2xl bg-white p-6 shadow-sm"><p className="break-words text-sm text-neutral-500">{l}</p><p className="mt-2 text-4xl font-bold">{v}</p></article>)}</div>}
  {tab==="analytics"&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-neutral-500">Просмотров</p><p className="mt-2 text-4xl font-bold">{views.length}</p></article><article className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-neutral-500">Уникальных посетителей</p><p className="mt-2 text-4xl font-bold">{analytics.unique}</p></article></div><section className="rounded-2xl bg-white p-5 shadow-sm"><h3 className="text-lg font-bold">Реферальные ссылки</h3><p className="mt-1 text-sm text-neutral-500">Создайте код и отправьте ссылку. Переходы появятся ниже в разделе «Реферальные коды».</p><div className="mt-4 flex flex-wrap gap-2"><input value={refCode} onChange={e=>setRefCode(slugify(e.target.value))} className="min-w-0 flex-1 rounded-xl border px-4 py-3" placeholder="partner-01"/><button onClick={async()=>{const url=`https://vasiliy2197463-jpg.github.io/exclusive-store-project-7/${locale}/?utm_source=referral&ref=${refCode||"partner-01"}`;await navigator.clipboard.writeText(url);setNotice("Реферальная ссылка скопирована")}} className="rounded-xl bg-black px-5 py-3 text-white">Скопировать ссылку</button></div></section>{views.length?<><div className="grid gap-4 md:grid-cols-2">{[["Источники трафика",analytics.sources],["Реферальные коды",analytics.refs],["Страницы входа",analytics.entries],["Страницы выхода",analytics.exits],["Устройства",analytics.devices],["Платформы",analytics.platforms],["Посещённые страницы",analytics.pages]].map(([title,items])=><section key={String(title)} className="min-w-0 rounded-2xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-bold">{String(title)}</h3><div className="space-y-3">{(items as [string,number][]).slice(0,12).map(([name,count])=><div key={name} className="flex min-w-0 items-center justify-between gap-3 border-b pb-2"><span className="min-w-0 break-all text-sm">{name}</span><b>{count}</b></div>)}</div></section>)}</div><section className="overflow-x-auto rounded-2xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-bold">Последние действия посетителей</h3><table className="min-w-[760px] w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Когда</th><th className="p-2">Источник / код</th><th className="p-2">Страница</th><th className="p-2">Вход</th><th className="p-2">Устройство</th></tr></thead><tbody>{views.slice(0,100).map(v=><tr key={v.id} className="border-b"><td className="p-2 whitespace-nowrap">{new Date(v.created_at).toLocaleString("ru-RU")}</td><td className="p-2 break-all">{v.source}{v.ref_code?` / ${v.ref_code}`:""}</td><td className="p-2 break-all">{v.path}</td><td className="p-2 break-all">{v.entry_path}</td><td className="p-2">{v.device} · {v.platform}</td></tr>)}</tbody></table></section></>:empty("Статистика начнёт собираться после подключения таблицы аналитики")}</div>}
  {tab==="products"&&<div className="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]"><form onSubmit={addProduct} className="h-fit rounded-2xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-xl font-bold">Новый товар</h3>{fields(form,setForm)}<button disabled={saving} className="mt-3 w-full rounded-xl bg-black p-3 font-semibold text-white">{saving?"Сохраняем…":"Добавить товар"}</button></form><section><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти товар…" className="mb-4 w-full rounded-full border bg-white px-5 py-3"/>{productList(visible)}</section></div>}
  {editing&&<div className="fixed inset-0 z-[200] overflow-y-auto bg-black/60 p-4"><form onSubmit={saveProduct} className="mx-auto my-8 max-w-xl rounded-3xl bg-white p-6"><div className="mb-5 flex items-center justify-between gap-3"><h3 className="text-2xl font-bold">Изменить товар</h3><button type="button" onClick={()=>setEditing(null)} className="rounded-full border px-4 py-2">Закрыть</button></div>{fields(editForm,setEditForm)}<button disabled={saving} className="mt-4 w-full rounded-xl bg-black p-3 font-semibold text-white">Сохранить</button></form></div>}
  {tab==="stock"&&(inventory.length?<div className="grid gap-3">{inventory.map(p=>{const amount=stockDraft[p.id]??p.stock,changed=amount!==p.stock;return <article key={p.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-5"><div className="flex min-w-0 items-center gap-4">{thumb(p)}<div className="min-w-0"><b className="break-words">{p.name}</b><p className={`text-sm ${amount<=5?"text-red-600":"text-neutral-500"}`}>{amount===0?"Нет в наличии":`Остаток: ${amount}`}</p></div></div><div className="flex flex-wrap items-center justify-end gap-2"><button onClick={()=>setStockDraft(d=>({...d,[p.id]:Math.max(0,amount-1)}))} className="h-10 w-10 rounded-full border">−</button><b className="min-w-10 py-2 text-center">{amount}</b><button onClick={()=>setStockDraft(d=>({...d,[p.id]:amount+1}))} className="h-10 w-10 rounded-full bg-black text-white">+</button><button disabled={!changed} onClick={async()=>{await updateProduct(p,{stock:amount},"Остаток сохранён");setStockDraft(d=>{const next={...d};delete next[p.id];return next})}} className="ml-1 rounded-full bg-black px-4 py-2 text-sm text-white disabled:cursor-not-allowed disabled:bg-neutral-200 disabled:text-neutral-500">Сохранить</button></div></article>})}</div>:empty("Товаров пока нет"))}
  {tab==="trash"&&productList(trash,true)}
  {tab==="promos"&&(promos.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{promos.map(p=>{const active=promoDraft[p.code]??p.active,changed=active!==p.active;return <article key={p.code} className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-neutral-500">Промокод</p><h3 className="mt-1 text-2xl font-black">{p.code}</h3><p className="mt-4 text-5xl font-black">{p.discount_percent}%</p><button onClick={()=>setPromoDraft(d=>({...d,[p.code]:!active}))} className={`mt-5 w-full rounded-xl p-3 font-semibold ${active?"bg-black text-white":"bg-neutral-200"}`}>{active?"Включён — отключить":"Отключён — включить"}</button><button disabled={!changed} onClick={()=>savePromo(p)} className="mt-2 w-full rounded-xl border border-black p-3 font-semibold disabled:cursor-not-allowed disabled:border-neutral-200 disabled:text-neutral-400">Сохранить</button></article>})}</div>:empty("Промокоды SALE20, SALE30, SALE50 и SALE70 появятся после миграции"))}
  {tab==="orders"&&(orders.length?<div className="space-y-4">{orders.map(o=><article key={o.id} className="rounded-2xl bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-neutral-500">#{o.id.slice(0,8)} · {new Date(o.created_at).toLocaleString("ru-RU")}</p><h3 className="mt-1 text-xl font-bold">{o.customer_name||"Покупатель"}</h3><p className="break-all text-sm">{o.customer_email} · {o.customer_phone}</p><p className="mt-2 text-sm">{o.shipping_address}</p></div><div className="text-right"><p className="text-2xl font-bold">{Number(o.total).toLocaleString("ru-RU")} ₽</p><select value={o.status} onChange={e=>changeStatus(o.id,e.target.value)} className="mt-3 rounded-xl border px-3 py-2">{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div></article>)}</div>:empty("Заказов пока нет"))}
  {tab==="customers"&&(customers.length?<div className="overflow-x-auto rounded-2xl bg-white"><table className="min-w-full text-left"><thead><tr className="border-b"><th className="p-4">Имя</th><th className="p-4">Телефон</th><th className="p-4">Роль</th><th className="p-4">Дата</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-b"><td className="p-4">{c.full_name||"Без имени"}</td><td className="p-4">{c.phone||"—"}</td><td className="p-4">{c.role}</td><td className="p-4">{new Date(c.created_at).toLocaleDateString("ru-RU")}</td></tr>)}</tbody></table></div>:empty("Клиентов пока нет"))}
  {tab==="support"&&(threads.length?<div className="grid gap-3">{threads.map(t=><article key={t.id} className="rounded-2xl bg-white p-5"><b>Обращение #{t.id.slice(0,8)}</b><p className="text-sm text-neutral-500">{new Date(t.last_message_at).toLocaleString("ru-RU")} · {t.status}</p></article>)}</div>:empty("Обращений пока нет"))}
  </main></div></div>;
}
