create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  path text not null,
  entry_path text not null default '',
  source text not null default 'direct',
  referrer text not null default '',
  device text not null default 'desktop',
  platform text not null default 'unknown',
  created_at timestamptz not null default now()
);

alter table public.page_views enable row level security;
drop policy if exists "anyone records page views" on public.page_views;
create policy "anyone records page views" on public.page_views for insert with check (true);
drop policy if exists "staff reads page views" on public.page_views;
create policy "staff reads page views" on public.page_views for select using (public.is_staff());
create index if not exists page_views_created_idx on public.page_views(created_at desc);
create index if not exists page_views_visitor_idx on public.page_views(visitor_id);
create index if not exists page_views_source_idx on public.page_views(source);

select 'analytics_ready' as status;
