alter table public.products add column if not exists archived boolean not null default false;

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent integer not null check (discount_percent in (20,30,50,70)),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.promo_codes (code,discount_percent,active)
values ('SALE20',20,true),('SALE30',30,true),('SALE50',50,true),('SALE70',70,true)
on conflict (code) do update set discount_percent=excluded.discount_percent;

alter table public.promo_codes enable row level security;
drop policy if exists "public reads active promos" on public.promo_codes;
create policy "public reads active promos" on public.promo_codes for select using (active or public.is_staff());
drop policy if exists "staff manage promos" on public.promo_codes;
create policy "staff manage promos" on public.promo_codes for all using (public.is_staff()) with check (public.is_staff());
create index if not exists products_archived_active_idx on public.products(archived,active);
