create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_slug text not null,
  product_name text not null,
  user_id uuid references auth.users(id) on delete set null,
  author_name text not null check (char_length(author_name) between 1 and 80),
  rating smallint not null check (rating between 1 and 5),
  body text not null check (char_length(body) between 1 and 2000),
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  admin_reply text not null default '',
  replied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_reviews enable row level security;
grant usage on schema public to anon, authenticated;
grant insert on table public.product_reviews to anon, authenticated;
grant select on table public.product_reviews to anon, authenticated;
grant update, delete on table public.product_reviews to authenticated;
grant usage, select on sequence public.product_reviews_id_seq to anon, authenticated;

drop policy if exists "public reads published reviews" on public.product_reviews;
create policy "public reads published reviews"
on public.product_reviews for select
to anon, authenticated
using (status = 'published' or public.is_staff());

drop policy if exists "visitors submit reviews" on public.product_reviews;
create policy "visitors submit reviews"
on public.product_reviews for insert
to anon, authenticated
with check (status = 'pending' and admin_reply = '');

drop policy if exists "staff moderates reviews" on public.product_reviews;
create policy "staff moderates reviews"
on public.product_reviews for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "staff deletes reviews" on public.product_reviews;
create policy "staff deletes reviews"
on public.product_reviews for delete
to authenticated
using (public.is_staff());

create index if not exists product_reviews_product_idx on public.product_reviews(product_slug, status, created_at desc);
create index if not exists product_reviews_status_idx on public.product_reviews(status, created_at desc);

select 'product_reviews_ready' as status;
