create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'customer' check (role in ('customer','support','manager','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  category text not null default '',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2),
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'new' check (status in ('new','confirmed','paid','processing','shipped','delivered','cancelled','refunded')),
  total numeric(12,2) not null default 0,
  customer_name text not null default '',
  customer_email text not null default '',
  customer_phone text not null default '',
  shipping_address text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  status text not null default 'open' check (status in ('open','in_progress','waiting_customer','closed')),
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.support_threads(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 4000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'phone', '')
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('support','manager','admin')
  );
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.support_threads enable row level security;
alter table public.support_messages enable row level security;

create policy "profiles read own" on public.profiles for select using (id = auth.uid() or public.is_staff());
create policy "profiles update own" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "products public read" on public.products for select using (active or public.is_staff());
create policy "products staff manage" on public.products for all using (public.is_staff()) with check (public.is_staff());
create policy "orders read own" on public.orders for select using (user_id = auth.uid() or public.is_staff());
create policy "orders create own" on public.orders for insert with check (user_id = auth.uid());
create policy "orders staff update" on public.orders for update using (public.is_staff());
create policy "threads read own" on public.support_threads for select using (user_id = auth.uid() or public.is_staff());
create policy "threads create own" on public.support_threads for insert with check (user_id = auth.uid());
create policy "threads staff update" on public.support_threads for update using (public.is_staff());
create policy "messages read thread" on public.support_messages for select using (
  exists (select 1 from public.support_threads t where t.id = thread_id and (t.user_id = auth.uid() or public.is_staff()))
);
create policy "messages create thread" on public.support_messages for insert with check (
  sender_id = auth.uid() and exists (select 1 from public.support_threads t where t.id = thread_id and (t.user_id = auth.uid() or public.is_staff()))
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists support_messages_thread_created_idx on public.support_messages(thread_id, created_at);
