create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

alter table public.order_items enable row level security;

drop policy if exists "order items read own" on public.order_items;
create policy "order items read own" on public.order_items for select using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and (orders.user_id = auth.uid() or public.is_staff())
  )
);

drop policy if exists "order items create own" on public.order_items;
create policy "order items create own" on public.order_items for insert with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id and orders.user_id = auth.uid()
  )
);

drop policy if exists "order items staff manage" on public.order_items;
create policy "order items staff manage" on public.order_items for all
using (public.is_staff()) with check (public.is_staff());

create index if not exists order_items_order_idx on public.order_items(order_id);
